// Generated by CoffeeScript 2.5.1
var File, fs;

fs = require("fs");

//fs = Fs.promises
module.exports = File = class File {
  constructor(path) {
    this.path = path;
  }

  async read(...args) {
    await fs.readFileSync(this.path, ...args);
    return this;
  }

  write(data, ...args) {
    fs.writeFileSync(this.path, data, ...args);
    return this;
  }

  exists() {
    return fs.existsSync(this.path);
  }

  mkpath() {
    var s;
    s = this.path.split("/").slice(0).join("/");
    fs.mkdirSync(s, {
      recursive: true
    });
    return this;
  }

};
