// Generated by CoffeeScript 2.5.1
var CSON, ESC, File, app, dumper, e, layout, port;

dumper = require('dumper').dumper;

CSON = require('cson');

File = require('./file');

app = require("express")();

ESC = {
  '<': '&lt;',
  '>': '&gt;',
  '\'': '&#;',
  '"': '&quot;',
  '&': '&amp;'
};

e = function(s) {
  return s.replace(/[<>'"&]/g, function(a) {
    return ESC[a];
  });
};

layout = function(s, p) {
  if (p == null) {
    p = {};
  }
  return `<!doctype html>
<html>
<head>
	<title>${p.title || "нет"} | Sofia</title>
</head>
<body>
	<table style='width:100%'>
	<tr>
		<td rowspan=2>Sofia
		<td>
			<form action="/search">
				<input name='s' placeholder='Искать эон'>
			</form>
	<tr>
		<td>${s}
	</table>
</body>`;
};

// Отображает эон с диска
app.get('/aeon/:aeon', function(req, res) {
  var a, aeon, e_aeon, f;
  aeon = req.params.aeon;
  f = new File(`pleroma/${aeon}/aeon.cson`);
  e_aeon = e(aeon);
  if (!f.exists()) {
    return res.send(layout(`Эона <a href="/aeon/create/${e_aeon}">${e_aeon}</a> нет.`));
  } else {
    a = CSON.parse(f.read());
    return res.send(layout(``));
  }
});

app.get('/aeon/create/:aeon', async function(req, res) {
  var aeon;
  aeon = req.params.aeon;
  ((await new File(`pleroma/${aeon}/aeon.cson`).mkpath())).write(CSON.stringify({}));
  return res.redirect('/aeon/#{aeon}');
});

port = 3000;

app.listen(port, function() {
  return console.log(`Example app listening at http://localhost:${port}`);
});
